services:
  fast-wwebjs-docker:
    init: true
    # command: sh -c "if [ \"$AMBIENT\" = 'production' ]; then npm run start:prod; else npm start; fi"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-wwebjs-docker
    volumes:
      - ./auth:/app/auth
    restart: always
    env_file:
      - path: .env
    ports:
      - "${PORT}:${PORT}"

